export const ACT_DINING_TABLE_EDITOR_CCS_START = "ACT_DINING_TABLE_EDITOR_CCS_START";
export const ACT_DINING_TABLE_EDITOR_CCS_CHAR = "ACT_DINING_TABLE_EDITOR_CCS_CHAR";
export const ACT_DINING_TABLE_CREATOR_CCS_CONFIRM = "ACT_DINING_TABLE_CREATOR_CCS_CONFIRM";
export const ACT_DINING_TABLE_EDITOR_CCS_CONFIRM = "ACT_DINING_TABLE_EDITOR_CCS_CONFIRM";
export const ACT_DINING_TABLE_EDITOR_CCS_ABORT = "ACT_DINING_TABLE_EDITOR_CCS_ABORT";

