export const FLOAT_EDITOR_START = "FLOAT_EDITOR_START";
export const FLOAT_EDITOR_CHAR = "FLOAT_EDITOR_CHAR";
export const FLOAT_EDITOR_CONFIRM = "FLOAT_EDITOR_CONFIRM";
export const FLOAT_EDITOR_ABORT = "FLOAT_EDITOR_ABORT";
