export const ACT_RETRIEVE_WAITER_STATUSES = "ACT_RETRIEVE_WAITER_STATUSES";
export const ACT_RETRIEVE_DISH_STATUSES = "ACT_RETRIEVE_DISH_STATUSES";

//Tables
export const ACT_RETRIEVE_RESTAURANT_TABLES = "ACT_RETRIEVE_RESTAURANT_TABLES";

//Customers
export const ACT_RETRIEVE_CUSTOMERS = "ACT_RETRIEVE_CUSTOMERS";

//Waiters
export const ACT_RETRIEVE_WAITERS = "ACT_RETRIEVE_WAITERS";

//Additions
export const ACT_RETRIEVE_ADDITIONS = "ACT_RETRIEVE_ADDITIONS";

//Categories
export const ACT_RETRIEVE_CATEGORIES = "ACT_RETRIEVE_CATEGORIES";
export const ACT_RETRIEVE_CURRENT_MENU = "ACT_RETRIEVE_CURRENT_MENU";

//Dishes
export const ACT_RETRIEVE_DISHES = "ACT_RETRIEVE_DISHES";

//Phases
export const ACT_RETRIEVE_PHASES = "ACT_RETRIEVE_PHASES";

//DiningTables

export const ACT_BEGIN_DINING_TABLE_DATA_EDITING = "ACT_BEGIN_DINING_TABLE_DATA_EDITING";
export const ACT_ABORT_DINING_TABLE_DATA_EDITING = "ACT_ABORT_DINING_TABLE_DATA_EDITING";

export const ACT_BEGIN_DINING_TABLE_BILLS_EDITING = "ACT_BEGIN_DINING_TABLE_BILLS_EDITING";
export const ACT_ABORT_DINING_TABLE_BILLS_EDITING = "ACT_ABORT_DINING_TABLE_BILLS_EDITING";

export const ACT_DELETE_DINING_TABLE = "ACT_DELETE_DINING_TABLE";


export const ACT_SELECT_BILL = "ACT_SELECT_BILL";
export const ACT_DESELECT_BILL = "ACT_DESELECT_BILL";
export const ACT_DELETE_BILL = "ACT_DELETE_BILL";

//Ordinations
export const ACT_CREATE_ORDINATION = "ACT_CREATE_ORDINATION";
export const ACT_DELETE_ORDINATION = "ACT_DELETE_ORDINATION";
export const ACT_UPDATE_ORDINATION = "ACT_UPDATE_ORDINATION";


//Printers

//PAGE
export const ACT_PRINTERS_PAGE_SELECT_PAGE = "ACT_PRINTERS_PAGE_SELECT_PAGE";

//CREATOR
//Name
export const ACT_PRINTER_CREATOR_NAME_ABORT = "ACT_PRINTER_CREATOR_NAME_ABORT";
export const ACT_UPDATE_PRINTER_CREATOR_NAME = "ACT_UPDATE_PRINTER_CREATOR_NAME";
//Main
export const ACT_UPDATE_PRINTER_CREATOR_MAIN = "ACT_UPDATE_PRINTER_CREATOR_MAIN";
//LineCharacters
export const ACT_PRINTER_CREATOR_LC_ABORT = "ACT_PRINTER_CREATOR_LC_ABORT";
export const ACT_UPDATE_PRINTER_CREATOR_LC = "ACT_UPDATE_PRINTER_CREATOR_LC";

export const ACT_RETRIEVE_PRINTERS = "ACT_RETRIEVE_PRINTERS";
export const ACT_RETRIEVE_PRINTER_SERVICES = "ACT_RETRIEVE_PRINTER_SERVICES";
export const ACT_CREATE_PRINTER = "ACT_CREATE_PRINTER";
export const ACT_UPDATE_PRINTER = "ACT_UPDATE_PRINTER";
export const ACT_DELETE_PRINTER = "ACT_DELETE_PRINTER";
export const ACT_SELECT_PRINTER = "ACT_SELECT_PRINTER";
export const ACT_DESELECT_PRINTER = "ACT_DESELECT_PRINTER";
export const ACT_BEGIN_CREATE_PRINTER = "ACT_BEGIN_CREATE_PRINTER";

//Locations
export const ACT_RETRIEVE_LOCATIONS = "ACT_RETRIEVE_LOCATIONS";
export const ACT_RETRIEVE_LOCATION_SERVICES = "ACT_RETRIEVE_LOCATION_SERVICES";


//FailedStore
export const ACT_REMOVE_FAILED_ACTION = "ACT_REMOVE_FAILED_ACTION";

export const ACT_CLEAR_ERROR_MESSAGES = "ACT_CLEAR_ERROR_MESSAGES";

//Inputs
export const ACT_FLOAT_INPUT_DIGIT = "ACT_FLOAT_INPUT_DIGIT";
export const ACT_FLOAT_INPUT_SET_VALUE = "ACT_FLOAT_INPUT_SET_VALUE";
export const ACT_OPEN_EDITOR = "ACT_OPEN_EDITOR";
export const ACT_CLOSE_EDITOR = "ACT_CLOSE_EDITOR";