export const ACT_EVENING_EDITOR_CC_START = "ACT_EVENING_EDITOR_CC_START";
export const ACT_EVENING_EDITOR_CC_CHAR = "ACT_EVENING_EDITOR_CC_CHAR";
export const ACT_EVENING_EDITOR_CC_CONFIRM = "ACT_EVENING_EDITOR_CC_CONFIRM";
export const ACT_EVENING_EDITOR_CC_ABORT = "ACT_EVENING_EDITOR_CC_ABORT";