export const Actions = {
    BEGIN_DINING_TABLE_CREATION: "BEGIN_DINING_TABLE_CREATION",
    CREATE_DINING_TABLE: "CREATE_DINING_TABLE",
    ABORT_DINING_TABLE_CREATION: "ABORT_DINING_TABLE_CREATION",

    SELECT_DINING_TABLE: "SELECT_DINING_TABLE",
    DESELECT_DINING_TABLE: "DESELECT_DINING_TABLE",

    BEGIN_CCS_EDITING : "BEGIN_CCS_EDITING",
    CCS_CHANGE : "CCS_CHANGE",
    CCS_CHAR : "CCS_CHAR",
    ABORT_CCS : "ABORT_CCS",
    CONFIRM_CREATOR_CCS : "CONFIRM_CREATOR_CCS",
    CONFIRM_CCS : "CONFIRM_CCS",

    BEGIN_WAITER_EDITING : "BEGIN_WAITER_EDITING",
    SELECT_WAITER_PAGE : "SELECT_WAITER_PAGE",
    SELECT_WAITER : "SELECT_WAITER",
    CONFIRM_WAITER : "CONFIRM_WAITER",
    CONFIRM_CREATOR_WAITER : "CONFIRM_CREATOR_WAITER",
    ABORT_WAITER : "ABORT_WAITER",

    BEGIN_TABLE_EDITING : "BEGIN_TABLE_EDITING",
    SELECT_TABLE_PAGE : "SELECT_TABLE_PAGE",
    SELECT_TABLE : "SELECT_TABLE",
    ABORT_TABLE : "ABORT_TABLE",
    CONFIRM_TABLE : "CONFIRM_TABLE",
    CONFIRM_CREATOR_TABLE : "CONFIRM_CREATOR_TABLE"
}